Repository DDD-Community/28.8-Android, pull requests merged in 2023-01, with the labels that each got.

#23 #16 : 차량연료 선택 ui, chip 컴포넌트 추가
  core-designsystem/src/main/java/com/ddd/carssok/core/designsystem/component/Appbar.kt
  core-designsystem/src/main/java/com/ddd/carssok/core/designsystem/component/BottomNavigation.kt
  core-designsystem/src/main/java/com/ddd/carssok/core/designsystem/component/CarssokButton.kt
  core-designsystem/src/main/java/com/ddd/carssok/core/designsystem/component/Chip.kt
  core-designsystem/src/main/java/com/ddd/carssok/core/designsystem/component/Dialog.kt
  core-designsystem/src/main/java/com/ddd/carssok/core/designsystem/component/RadioButton.kt
  core-designsystem/src/main/java/com/ddd/carssok/core/designsystem/component/TypoText.kt
  core-designsystem/src/main/res/values/colors.xml
  feature/onboarding/src/main/java/com/ddd/carssok/feature/onboarding/brand/OnBoardingBrandScreen.kt
  feature/onboarding/src/main/java/com/ddd/carssok/feature/onboarding/fuel/OnBoardingFuelScreen.kt
  feature/onboarding/src/main/java/com/ddd/carssok/feature/onboarding/fuel/OnBoardingFuelViewModel.kt
  feature/onboarding/src/main/java/com/ddd/carssok/feature/onboarding/model/OnBoardingModelScreen.kt
  feature/onboarding/src/main/res/values/strings.xml
Labels: 온보딩

#24 기록하기 BottomSheet 추가
  .idea/gradle.xml
  app/build.gradle.kts
  app/src/main/java/com/ddd/carssok/CarssokApp.kt
  app/src/main/java/com/ddd/carssok/CarssokAppState.kt
  app/src/main/java/com/ddd/carssok/navigation/CarssokNavHost.kt
  core-designsystem/src/main/java/com/ddd/carssok/core/designsystem/component/BottomNavigation.kt
  core-designsystem/src/main/java/com/ddd/carssok/core/designsystem/component/BottomSheet.kt
  core-designsystem/src/main/res/drawable/ic_arrow_right_12.xml
  core-designsystem/src/main/res/drawable/ic_drag_handle.xml
  core-designsystem/src/main/res/drawable/ic_refuel.xml
  feature/onboarding/src/main/java/com/ddd/carssok/feature/onboarding/fuel/OnBoardingFuelScreen.kt
  feature/record/src/main/java/com/ddd/carssok/feature/record/RecordBottomSheet.kt
  feature/record/src/main/java/com/ddd/carssok/feature/record/accident/RecordAccidentScreen.kt
  feature/record/src/main/java/com/ddd/carssok/feature/record/drive/RecordDriveScreen.kt
  feature/record/src/main/java/com/ddd/carssok/feature/record/maintenance/RecordMaintenanceScreen.kt
  feature/record/src/main/java/com/ddd/carssok/feature/record/navi/RecordDestination.kt
  feature/record/src/main/java/com/ddd/carssok/feature/record/navi/RecordNavItem.kt
  feature/record/src/main/java/com/ddd/carssok/feature/record/refuel/RecordRefuelScreen.kt
  feature/record/src/main/res/values/strings.xml
Labels: 기록하기

#28 [#27] 주행기록하기 ui화면 개발
  core-designsystem/src/main/java/com/ddd/carssok/core/designsystem/Typo.kt
  core-designsystem/src/main/java/com/ddd/carssok/core/designsystem/component/Appbar.kt
  core-designsystem/src/main/java/com/ddd/carssok/core/designsystem/component/Dialog.kt
  core-designsystem/src/main/java/com/ddd/carssok/core/designsystem/component/TypoText.kt
  core-designsystem/src/main/res/drawable-night/ic_arrow_back_circle_32.xml
  core-designsystem/src/main/res/drawable-xhdpi/ic_record_drive_car.png
  core-designsystem/src/main/res/drawable-xxhdpi/ic_record_drive_car.png
  core-designsystem/src/main/res/drawable-xxxhdpi/ic_record_drive_car.png
  core-designsystem/src/main/res/drawable/ic_arrow_back_circle_32.xml
  feature/record/src/main/java/com/ddd/carssok/feature/record/accident/RecordAccidentScreen.kt
  feature/record/src/main/java/com/ddd/carssok/feature/record/drive/RecordDriveDialog.kt
  feature/record/src/main/java/com/ddd/carssok/feature/record/drive/RecordDriveScreen.kt
  feature/record/src/main/java/com/ddd/carssok/feature/record/drive/RecordDriveViewModel.kt
  feature/record/src/main/java/com/ddd/carssok/feature/record/navi/RecordDestination.kt
  feature/record/src/main/res/values/strings.xml
Labels: 기록하기

#30 #6: network 구성 & flipper 연동, token api 연동
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ddd/carssok/CarssokApplication.kt
  buildSrc/src/main/kotlin/Dep.kt
  core-data/build.gradle.kts
  core-data/src/main/java/com/ddd/carssok/core/data/CoroutinesQualifiers.kt
  core-data/src/main/java/com/ddd/carssok/core/data/di/DispatcherModule.kt
  core-data/src/main/java/com/ddd/carssok/core/data/di/OnboardingModule.kt
  core-data/src/main/java/com/ddd/carssok/core/data/model/UserToken.kt
  core-data/src/main/java/com/ddd/carssok/core/data/repository/account/AccountRepository.kt
  core-data/src/main/java/com/ddd/carssok/core/data/repository/onboarding/FakeOnBoardingRepositoryImpl.kt
  core-datastore/src/main/java/com/ddd/carssok/datastore/CarssokDataStore.kt
  core-datastore/src/main/java/com/ddd/carssok/datastore/CarssokDataStoreImpl.kt
  core-datastore/src/main/java/com/ddd/carssok/datastore/di/DataStoreModule.kt
  core-network/build.gradle.kts
  core-network/src/main/java/com/ddd/carssok/core/network/api/AuthApi.kt
  core-network/src/main/java/com/ddd/carssok/core/network/di/ApiModule.kt
  core-network/src/main/java/com/ddd/carssok/core/network/di/NetworkModule.kt
  core-network/src/main/java/com/ddd/carssok/core/network/model/AuthRequestBody.kt
  core-network/src/main/java/com/ddd/carssok/core/network/model/UserTokenResponse.kt
  feature/onboarding/src/main/java/com/ddd/carssok/feature/onboarding/OnBoardingViewModel.kt
  feature/onboarding/src/main/java/com/ddd/carssok/feature/onboarding/brand/OnBoardingBrandViewModel.kt
  feature/onboarding/src/main/java/com/ddd/carssok/feature/onboarding/fuel/OnBoardingFuelScreen.kt
Labels: 개발환경 세팅

#31 #6: network interceptor
  core-data/src/main/java/com/ddd/carssok/core/data/repository/account/AccountRepository.kt
  core-network/build.gradle.kts
  core-network/src/main/java/com/ddd/carssok/core/network/AuthInterceptor.kt
  core-network/src/main/java/com/ddd/carssok/core/network/CarssokErrorCode.kt
  core-network/src/main/java/com/ddd/carssok/core/network/CarssokException.kt
  core-network/src/main/java/com/ddd/carssok/core/network/api/AuthApi.kt
  core-network/src/main/java/com/ddd/carssok/core/network/di/NetworkModule.kt
  core-network/src/main/java/com/ddd/carssok/core/network/model/UserTokenResponse.kt
  feature/home/src/main/java/com/ddd/carssok/feature/home/HomeScreen.kt
  feature/home/src/main/java/com/ddd/carssok/feature/home/HomeViewModel.kt
  feature/onboarding/src/main/java/com/ddd/carssok/feature/onboarding/brand/OnBoardingBrandViewModel.kt
Labels: 개발환경 세팅
